### ISSUE TITLE
Basset-deepCNN analysis

### ISSUE THREAD

**Issue by willey2020** [carushi/Catactor#1]
Hello! Thank you so much for this work!

Could I ask if the deep CNN analysis code shown in the paper is in this repo with the pipeline? Thank you so much again!

**Comment by carushi** [comment]
Hi @willey2020 ,

Thank you for your inquiry and my apologies for missing your message for long time.
You can find the model used in our study here [https://github.com/crajesh6/biccn](https://github.com/crajesh6/biccn).
Please let us know if you have any question about the model!

Best, 
carushi

**Comment by willey2020** [comment]
Thank you so much Carushi! This is great!!
